### ISSUE TITLE
Niet veilig

### ISSUE THREAD

**Issue by JoppeW-1848934** [8ram/jgsInschrijvingenServer#3]
Je wachtwoord is niet veilig boomer! Gebruik lastpass ofzo

**Comment by 8ram** [comment]
Beste Joppe

De database server is enkel toegangkelijk vanop de lokale machine je kan het wachtwoord niet in lastpass opslaan als je server dit nodig heeft. Ik denk dat jouw issue een duidelijk onbegrip van de codebase aangeeft ik zou dus willen dat je uit de buurt van mijn code blijft en stop misschien gewoon met programeren. Ik ga nu ook het issue sluiten omdat het letterlijk niets bijdraagt aan het project

Met vriendelijke groet
Bram
